### ISSUE TITLE
Change the Icon

### ISSUE THREAD

**Issue by ItsBen12000** [cloneconf/xmedium#2]
First of all: App looks clean and works as intended
but the icon looks like the one from xvideos (p0rn-site) and this somehow triggers me :p

**Comment by cloneconf** [comment]
@ItsBen12000 Yes I can agree with you that both the name and icon is very suspicious :roll_eyes: 
I don't support p... in anyway, and my intention wasn't to trigger people.
And the `X` only meant that the app is `Cross-Platform`
However I understand what you mean...
Maybe changing the color from red, to another color might solve it?
Or the name too?
Any suggestions will be appreciate it ;)

**Comment by ItsBen12000** [comment]
Maybe you can set the X behind "Medium" and about the color you could actually also set it black.

**Comment by cloneconf** [comment]
Thanks for suggestion!
However I did named it `Nedium`, idk but i find somehow good
Since i did use nedium application id before (gh.cloneconf.nedium), now i am trying to reclaim it by removing the old one and use it again
I hope it works!
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10407

**Comment by cloneconf** [comment]
As result, this repo will be archive and the development will continue on [nedium](https://github.com/cloneconf/nedium).

**Comment by cloneconf** [comment]
nedium will be hopefully available after some days on fdroid.
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10411

If you have any other issues please open them in the repo ([nedium](https://github.com/cloneconf/nedium)) :heart:
